### ISSUE TITLE
Sneaky issue cursor error on backspace key

### ISSUE THREAD

**Issue by djtyroon** [RobinHerbots/Inputmask#156]
jquery.inputmask 2.X lastest :

Hello, when you press more than max digit, the regexp stop next entries all right but on backspace the cursor don't take the right place for eg:

repeat: 13,  with group separator ' ' and groupSize: 3 and numeric extension js file edit :

'integer2': {
            regex: {
                number: function (groupSeparator, groupSize) { return new RegExp("\d\s*$"); }
            },
            alias: "decimal"
        }

if i press 16 times on 9 number and one backspace the cursor is shifted to the left three characters instead of staying right

Sorry for my bad english, hard to explain for me.

Thanks

**Comment by RobinHerbots** [comment]
Hi djtyroon, 

numerics are still buggy for the moment, but the next milestone is dedicated to full support for numerics.

I will look at the issue soon.

Thx for reporting!!

best regards, 

Robin

**Comment by djtyroon** [comment]
Thanks you too

**Comment by weiribao** [comment]
Hi Robin,

We use inputmask in our project and encounter this issue as well. I created a fiddle to reproduce the bug. Not sure wether it helps but I will put the link here: [http://jsfiddle.net/wrb302/Qejuk/](http://jsfiddle.net/wrb302/Qejuk/)

Thanks,

Bruce

**Comment by RobinHerbots** [comment]
This issue is solbed but not committed, as I am further working on the
decimal mask.

I will commit it soon.

best regards,

Robin

2013/2/9 Bruce Wei notifications@github.com

**Comment by RobinHerbots** [comment]
Hi, 

The backspace issue is resolved.  
@weiribao 
I still have to look at the issues you mentioned in your jsFiddle.

I will fix that soon.

Best regards

Robin

**Comment by RobinHerbots** [comment]
Hi weiribao,

The issue in the jsfiddle are solved.

best regards, 

Robin

**Comment by weiribao** [comment]
Hi Robin,

Thanks for the fix. That was really fast!

It looks like there is still an issue when autoGroup is on. You can see it at the updated fiddle: [http://jsfiddle.net/Qejuk/5/](http://jsfiddle.net/Qejuk/5/)

**Comment by RobinHerbots** [comment]
Hi Bruce,

I see it, ... that is because the delete does not retrigger the autogroup
function.

I will also fix this one.

Robin

2013/2/22 Bruce Wei notifications@github.com

**Comment by RobinHerbots** [comment]
Hi weiribao, 

This is fixed in the latest version.

Best regards, 

Robin

**Comment by djtyroon** [comment]
Thanks Robin, my first issue is fixed.

Best,
