### ISSUE TITLE
Prefilling buffer within prevalidator loses characters (specifically with date mask)

### ISSUE THREAD

**Issue by jimithing277** [RobinHerbots/Inputmask#229]
I've recently upgraded your library to 2.x after we've been using version 1.7 for quite some time in our production build.

Recently, we've stumbled upon some behavior which we were not experiencing with v1.7 that I was hoping you could possibly look in to and shed some light.  First, let me explain what our desired behavior is:

In the previous version we added some logic to our date mask within the prevalidation so that upon entering the first character of the mask the rest of the date would prefill with the first date of the current month and year.

For example:

Entering the value '4' would essentially result in the following to be displayed in the input: '04/01/2013'.  The majority of the time our users are entering dates they are almost always choosing the first day of the current month.  This made it quite efficient for them as they did not have to worry about entering the remaining day or year...it was just prefilled for them.

Below is the code snippet for how I was previously performing this (I've hard-coded the buffer values for demonstration purposes):

(function ($) {

```
//Store the original prevalidator for use in our custom prevalidator
var origPreValidator = $.inputmask.defaults.aliases['dd/mm/yyyy'].definitions['1'].prevalidator[0].validator;

$.extend(true, $.inputmask.defaults.aliases, {
    'mm/dd/yyyy': {
        definitions: {
            '1': {
                prevalidator: [{
                    validator: function (chrs, buffer, pos, strict, opts) {
                        //Call the original prevalidator first
                        var result = origPreValidator(chrs, buffer, pos, strict, opts);
                        if (!result)
                            return result;

                        //set day to beginning of month
                        buffer[3] = '0';
                        buffer[4] = '1';

                        //set year to current year
                        buffer[6] = '2';
                        buffer[7] = '0';
                        buffer[8] = '1';
                        buffer[9] = '3';

                        return result;
                    }
                }]
            }
        }
    }
});
```

})(jQuery);

Upon upgrading to version 2.X when we now enter the value of '4' the input control shows the following value: '04/m1/2013'.  There appears to be an issue where the '0' within the day portion of the mask is getting stomped out.  I've traced this issue down to the following segment of code but unfortunately am having a tough time understanding what exactly it is doing and was hoping you could shed some light.  The issue appears to happen within the 'checkVal()' method.  Specifically, right at line 625 where you begin looping over the input value.  It seems that when 'pos' is equal to '3' the issue presents itself (by calling setReTargetPlaceHolder() line 637).

So, in the end we are anticipating that the input value would show '04/01/2013' with the cursor at the '0' of the day portion.  

Thanks for any help!

**Comment by RobinHerbots** [comment]
@jimithing277, 

The checkVal is a bit stricter as before, but something as below should fix it.

  var origPreValidator = $.inputmask.defaults.aliases['dd/mm/yyyy'].definitions['1'].prevalidator[0].validator;

```
        $.extend(true, $.inputmask.defaults.aliases, {
            'mm/dd/yyyy': {
                definitions: {
                    '1': {
                        prevalidator: [{
                            validator: function (chrs, buffer, pos, strict, opts) {
                                //Call the original prevalidator first
                                var result = origPreValidator(chrs, buffer, pos, strict, opts);
                                if (result && !strict) {
                                    //set result
                                    if(result !== true) buffer[result["pos"]] = chrs;

                                    //set day to beginning of month
                                    buffer[3] = '0';
                                    buffer[4] = '1';

                                    //set year to current year
                                    buffer[6] = '2';
                                    buffer[7] = '0';
                                    buffer[8] = '1';

                                    //buffer[9] = '3';
                                    result = { pos: 9, c: 3 };
                                }
                                return result;
                            }
                        }]
                    }
                }
            }
        });
```

**Comment by RobinHerbots** [comment]
@jimithing277 , 

Hmm, ... I will have a relook at the checkval as an input as 0m/01/2013 should be ok for checkVal.

**Comment by jimithing277** [comment]
Robin,

Thank you for the quick reply!  I appreciate your suggestion however it does still appear that there area a few issues even after attempting to use your solution.

1) It is desired that the cursor remain at position '3' when entering a first character between '2' and '9'.  When entering a value of '1' as the first character it would be desired that the cursor remain at position '1' so they could finish the month off ('10', '11', or '12').

2) If you attempt to enter a month starting with the '1' character you can see that the solution does not handle this case very gracefully.

3) Using your suggested solution, if I enter '4' the input will prefill correctly and display '04/01/2013'.  However, if I then put the cursor in the day portion and attempt to change the day to let's day '04/22/2013' the year portion is wiped out.  It is desired that the year portion would remain in tact while only changing the day.

Again, thank you for your help while looking in to this, I greatly appreciate it along with your patience.

**Comment by jimithing277** [comment]
Also, I wanted to point out that our previous version we were using was 1.2.2, not 1.7 as I stated earlier.  Sorry about that.

**Comment by RobinHerbots** [comment]
@jimithing277 ,

Can you retry with the latest version and the original extension you wrote

best regards, 

Robin

**Comment by jimithing277** [comment]
Robin,

After getting the latest version and using my original extension it still appears that the original issue is occurring where the '0' in the third buffer position (day portion of the mask) is being removed.  This occurs when entering '4' as the first character in the input.  Screen capture attached:

![5-1-2013 4-25-39 pm](https://f.cloud.github.com/assets/4098730/450865/63c0e756-b29d-11e2-9196-981c99d1bb4a.png)

**Comment by RobinHerbots** [comment]
try with 

   $.extend(true, $.inputmask.defaults.aliases, {
            'mm/dd/yyyy': {
                definitions: {
                    '1': {
                        prevalidator: [{
                            validator: function (chrs, buffer, pos, strict, opts) {
                                //Call the original prevalidator first
                                var result = origPreValidator(chrs, buffer, pos, strict, opts);
                                if (result && !strict) {
                                    //set result
                                    if(result !== true) buffer[result["pos"]] = chrs;

```
                                //set day to beginning of month
                                buffer[3] = '0';
                                buffer[4] = '1';

                                //set year to current year
                                buffer[6] = '2';
                                buffer[7] = '0';
                                buffer[8] = '1';

                                buffer[9] = '3';
                            }
                            return result;
                        }
                    }]
                }
            }
        }
    });
```

Anyway I will optimize the determineActiveMasksetIndex which causes the issue.

Robin

**Comment by RobinHerbots** [comment]
@jimithing277, 

My advise, revert to the 1.2.2 version, until I have fixed this in the 2.x branch.  This issue is currently my priority for the inputmask as it showed some issues in the multi-mask implememntation.

**Comment by jimithing277** [comment]
@RobinHerbots ,

Thank you for your time and help with this.  Fortunately our production build is still using 1.2.2 and we've only began testing with 2.x.  We greatly appreciate you efforts with the plugin as its by far the best masking plugin we've used.  

The only downside we had was that it didn't support multimasks but when we saw that was introduced in 2.x we began testing that version.

I'll keep my eye on any updates...

**Comment by RobinHerbots** [comment]
@jimithing277,

I am still working on it.  (see dev branch)  I am almost there but this new release will need a lot of testing as there are many many changes in the plugin. 

I you would have some time todo some testing of the dev branch that would always be welcome.

Robin

**Comment by RobinHerbots** [comment]
@jimithing277 ,

Can you retry with the latest version

best regards, 

Robin
