### ISSUE TITLE
min and max not working in datetime for 12 Hours format i.e. dd/mm/yyyy hh:MM:ss TT 

### ISSUE THREAD

**Issue by harshal-ringe** [RobinHerbots/Inputmask#2297]
- If we set min and max value for datetime input mask, it doesn't work for 12 hours datetime format. It works for 24 hours datetime format
- https://jsfiddle.net/ksjx7tpg/8/ 

`$("#datetime").inputmask('datetime', {    
    inputFormat: "dd/mm/yyyy hh:MM:ss TT",
    min: "30/03/2020 12:00:00 AM",
    max: "30/03/2020 11:59:59 PM",
  });
  $("#datetime").inputmask('setvalue', '30/03/2020 11:00:00 AM');`

- Inputmask version: 5.x

**Comment by dhanashree-chavan** [comment]
Hi @RobinHerbots ,

I am also facing the same issue and it is a measure issue. Will it be resolved soon? If not, is there any workaround to solve this.

**Comment by rgaikar-lilly** [comment]
Hello @RobinHerbots ,

I have below mask:

`  Inputmask('datetime', {
    inputFormat: 'mm / dd / yyyy',
    placeholder: 'MM / DD / YYYY',
    showMaskOnFocus: false,
    showMaskOnHover: false,
    clearMaskOnLostFocus: true,
    insertModeVisual: false,
    // jitMasking: true,
    min: '01 / 01 / 1900',
    max: Moment()
      .subtract(18, 'years')
      .format('MM / DD / YYYY')
  }).mask($('#dob'));`

If I keep jitmasking enabled, the min and max thing (Whole datetime mask )does not works. Any workaround on it?

I have to disable jitmasking to make it work. Please provide solution for this issue.

thanks

**Comment by RobinHerbots** [comment]
@harshal247software,

Yes the datetime does not handle the AM en PM correct.  This needs to be fixed.

**Comment by RobinHerbots** [comment]
@harshal247software ,

Can you have a try with version 5.0.7-beta.11.

**Comment by RobinHerbots** [comment]
@rgaikar-lilly ,

The jitmasking should now work together with the datetime alias.
Have a try with version 5.0.7-beta.12

**Comment by harshal-ringe** [comment]
> @harshal247software ,
> 
> Can you have a try with version 5.0.7-beta.11.

Hi @RobinHerbots ,

It is still not working. In JSFiddle, I'm using the latest version i.e 5.0.7-beta.12 and it still shows XM instead of AM after setting the value, Please check  [https://jsfiddle.net/ksjx7tpg/8/](https://jsfiddle.net/ksjx7tpg/8/)

**Comment by RobinHerbots** [comment]
@harshal247software ,

That is because 30/03/2020 11:00:00 AM  is smaller then the minimum you specified.  Only 30/03/2020 11:00:00 PM is valid in this case.

**Comment by harshal-ringe** [comment]
> @harshal247software ,
> 
> That is because 30/03/2020 11:00:00 AM is smaller then the minimum you specified. Only 30/03/2020 11:00:00 PM is valid in this case.

Hi @RobinHerbots ,

The given value is in the min-max range. 11:00 AM is greater than the minimum value provided which is 12:00 AM (00:00) midnight and less than the maximum value which is 11:59 PM(23:59). The range provided here is for the whole day of 30/03/2020 from 00:00 to 23:59. Please check 12 Hour [clock system table](https://en.wikipedia.org/wiki/12-hour_clock) on Wikipedia

**Comment by RobinHerbots** [comment]
Hi @harshal247software,

Offcourse, I was not thinking straight!
Who invented that ;-)

I will submit a patch today.

**Comment by RobinHerbots** [comment]
@harshal247software ,

5.0.7-beta.13
