### ISSUE TITLE
Error thrown, if only insert radixpoint and leave field and placeholder = ""

### ISSUE THREAD

**Issue by jodrescher** [RobinHerbots/Inputmask#2475]
The following error is thrown, if I entered only the radixpoint in the input field and leave it. The radixpoint is still in the field, better would be, to clear the field on blur for this case.

`Uncaught TypeError: Cannot read property 'forwardPosition'
at HTMLInputElement.blurEvent`

OS: macOS
Browser: current Chrome
Inputmask version: 5.0.5

**Comment by RobinHerbots** [comment]
@jodrescher , 

Can you give the exact mask and option you have used.
Thx,
Robin

**Comment by RobinHerbots** [comment]
@jodrescher,

Can you have a try with 5.0.6-beta.42 
I think this is already solved.

**Comment by jodrescher** [comment]
Hi, sorry for the late reply. I guess it's when you set the placeholder to an empty string. I tested it with 5.0.6-beta.42 and used the following mask. It still occurs

```
target.inputmask('numeric', {
        placeholder: ''
});
```

I hope this helps.

**Comment by RobinHerbots** [comment]
@jodrescher ,

Fixed

**Comment by RobinHerbots** [comment]
@jodrescher ,
Thx for the extra. Info on the issue.

**Comment by jodrescher** [comment]
thx for the fast fix :)
