### ISSUE TITLE
.val() should ignore configured fix-text in 'mask'-option

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#258]
See JSFiddle:
http://jsfiddle.net/bZT3j/

in my opinion the
$('#txtECodeContainer2').val('DE001');
should only add the 001 into the input but it put's the whole value.

with 2.2.18 it worked, see here:
http://jsfiddle.net/vpDds/

**Comment by RobinHerbots** [comment]
@wuSam , 

I totally agree!

I will fix it soon.

**Comment by RobinHerbots** [comment]
http://jsfiddle.net/bZT3j/2/

Fixed in the latest version.

Best regards, 
Robin

**Comment by ghost** [comment]
Hi,

this is somehow still an issue:
see here:
http://jsfiddle.net/bZT3j/5/

**Comment by ghost** [comment]
this is not yet fixed: http://jsfiddle.net/bZT3j/2/
sorry robin! :-(
