### ISSUE TITLE
#258 is not yet fixed

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#264]
see here:

https://github.com/RobinHerbots/jquery.inputmask/issues/258

and here:
http://jsfiddle.net/bZT3j/5/

**Comment by RobinHerbots** [comment]
@wuSam , 

That is because you give a partially unformatted value as input and the DE is valid input for the next input.

Putting in the spaces or leaving out the DE should work.

Anyway I will see if I can add some intelligence in the checkval ;-)  But it will always be a trade-off.

**Comment by ghost** [comment]
so it was wrong in minor-version .18 where this worked also without spaces in .val(xxx) ??

**Comment by RobinHerbots** [comment]
@wuSam , 

No what I mean, there will be always cases where the implementation of checkval wil fail.

But I will fix your case soon

**Comment by ghost** [comment]
updated jsfiddle:
http://jsfiddle.net/bZT3j/7/

**Comment by RobinHerbots** [comment]
@wuSam ,

Thx for the updated jsfiddle

**Comment by RobinHerbots** [comment]
@wuSam , 

Fixed

**Comment by ghost** [comment]
this is not yet fixed: http://jsfiddle.net/bZT3j/2/
sorry robin! :-(

**Comment by RobinHerbots** [comment]
yafix !!!  ;-)
