### ISSUE TITLE
Submit causes Change Event to fire

### ISSUE THREAD

**Issue by WaltDaniels** [RobinHerbots/Inputmask#325]
I've got 'change' listeners on a number of input fields on my page.  I notice that when the 'Submit' button is clicked the input fields with inputmasks defined fire their 'change' event.  I see in the code where you're doing that, however there is no "real" change occurring on the field, so why is the 'change' event being fired?  Can you suggest some way of filtering out these 'change' events?  Or perhaps an alternative event that I can listen for?

Markup:

``` html
<input class="rowStartDate mask-date k-input" type="text" value="09/01/2013" >
```

Event Handler:

``` javascript
$(document).on('change', 'input.rowStartDate', function() {
    //do something here
});
```

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

Can you retry with version 2.3.26

**Comment by WaltDaniels** [comment]
I will test with 2.3.26 once it is available via nuget, thanks!

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

available v 2.3.31

**Comment by WaltDaniels** [comment]
The change event fires for each field with an inputmask.  Line 936 of jquery.inputmaks-2-3-31.js is raising the event.

``` javascript
$input.closest('form').bind("submit", function () { //trigger change on submit if any
                        if ($input[0]._valueGet && $input[0]._valueGet() != getActiveMaskSet()["undoBuffer"]) {
                            $input.change();
                        }
```

**Comment by RobinHerbots** [comment]
fixed in 2.3.35

**Comment by WaltDaniels** [comment]
Thanks for the quick-fix Robin, but there's still an issue here.  This now works fine for any input fields that we've either entered values into or tabbed through.  However, the 'change' event still fires on input fields that have a value (from the server) but have not received focus.

**Comment by RobinHerbots** [comment]
@WaltDaniels , 

Shoudl be all fixed now in the latest version ;-)

**Comment by manrueda** [comment]
Hi @RobinHerbots 
with the last version this error happen again...

**Comment by RobinHerbots** [comment]
@ManRueda , 

With the latest dev?

**Comment by manrueda** [comment]
@RobinHerbots 

Yes, with the last of the master...

**Comment by RobinHerbots** [comment]
@ManRueda , 

Can you have a test with the latest dev.

**Comment by manrueda** [comment]
@RobinHerbots ,

Doing the same steps of the last time works perfect!
Thank!
