### ISSUE TITLE
Date mask allowing invalid year

### ISSUE THREAD

**Issue by DanaCris** [RobinHerbots/Inputmask#489]
Version: 2.5.10

You can enter a letter for any digit of the year except the first one.

Example of accepted dates:
23/09/2ygm
09/02/2f8i

Just like you can't enter a letter for the date or the month, I think it would be necessary to be the same for the year.

Thanks!

**Comment by RobinHerbots** [comment]
@DanaCris , 

Can you make a jsfiddle for that?

best regards, 

Robin

**Comment by DanaCris** [comment]
http://jsfiddle.net/fVv7a/8/

For example, if I introduce 11 for day, 11 for month and 2w for year (or 2 followed by any character) I get 11/11/202w.
I think the problem comes from using yearrange with a min of 0001 (as used by someone in the project I'm working on). With a minyear of 1, you can enter a character for any digit of the year except the first one.
The issue with letters accepted in the year appears only for a minyear of 0227 or lower, maxyear remaining 2999.

Regards,
Dana

**Comment by RobinHerbots** [comment]
@DanaCris , 

I will fix it soon.

**Comment by RobinHerbots** [comment]
Fixed in 3.x branch

**Comment by adelina1985a** [comment]
Has 3.x been officially released? in some files I see 0.0.0 as version.
Also, how can I still get bundle.min file if I can't find a /dist/ folder, please?

**Comment by RobinHerbots** [comment]
@adelina1985a 

Not yet, but I will release it soon.

**Comment by adelina1985a** [comment]
OK TIA

**Comment by DanaCris** [comment]
Thank you!
