### ISSUE TITLE
Another showMaskOnHover and showMaskOnFocus problem

### ISSUE THREAD

**Issue by nick-skriabin** [RobinHerbots/Inputmask#601]
Hello! The problem is that both `showMaskOnHover` and `showMaskOnFocus`
options doesn't work at all. 

``` javascript
$(function(){
    $('#card_number').inputmask('9999 9999 9999 9999[99]',{
        greedy: false,
        showMaskOnHover: false, // will do nothing, mask will be shown on hover
        showMaskOnFocus: false // also takes no effect
    });
});
```

``` html
<input type="text" id="card_number">
```

I tried different combinations of those properties with no luck. I also tried to pre-configure plugin by extending `$.inputmask.defaults` but it also does nothing.

**My system:**
OS X 10.10
Google Chrome Version 37.0.2062.58 beta

**Also tested on:**
Windows 7
Google Chrome Version 36.0.1985.125 m

**Inputmask version from master (v3.0.60)**

Here is a fiddle: http://jsfiddle.net/pnL3veks/1/

**UPD** I tried version 3.0.55, everything fine, properties works as expected.

**Comment by RobinHerbots** [comment]
@nicholasrq , 

Fixed in version 3.0.61

**Comment by Ciwan1859** [comment]
I'm using the latest version, and I still have this problem. The default state for **showMaskOnFocus** is **true**, yet even though I am not focused on the input in question, the mask is still shown!

I'm not sure if this is because I'm using the data attributes like this:

`@Html.EditorFor(model => model.ShippingCost, new { htmlAttributes = new { @class = "form-control", data_inputmask = "'mask': '¥ 9{*}[.9{*}]'" } })`

It is in ASP.net MVC Razor view.

**Comment by Umadevijuvva** [comment]
showMaskOnHover and showMaskOnFocus  not working in MAC safari.I am using the latest version of JS file,Can someone help on this please?

**Comment by RobinHerbots** [comment]
@Umadevijuvva ,

Can you comment on issue #1488.  Otherwise I will forget about it.

**Comment by Umadevijuvva** [comment]
Hello,

I commented on the issue mentioned by you,along with my code snippet.Thanks in advance for providing a solution.

**Comment by RobinHerbots** [comment]
Hi,

Ok,  that is great.  I don't have much time at the moment but I will
definitely look into it

Op vr 10 feb. 2017 om 10:55 schreef Umadevijuvva <notifications@github.com>:

**Comment by Umadevijuvva** [comment]
Hi Robin,

Did you get any time to look in to the issue in Safari for showMaskOnHover and showMaskOnFocus ?

**Comment by Umadevijuvva** [comment]
Dear Robin,

Sorry to say its getting really urgent to fix this otherwise i have to revert my code and find another solution.Could you please let me know if this is fixable so that i can already start working on the other solutions in worst case.

Thanks in advance for your reply.
