### ISSUE TITLE
phone mask error (mult mask)

### ISSUE THREAD

**Issue by penihel** [RobinHerbots/Inputmask#628]
Continuing issue #549 
View http://jsfiddle.net/8wjsscj0/

I have a error when set the value of input.

i have a observable (ko) with "(12) 1234-1234" value

Set set to input, but the result is "(12) 12341-234_"

I expected "(12) 1234-1234"

Could understand the problem?

**Comment by RobinHerbots** [comment]
@penihel , 

I will have a look at it.  Also see #627

**Comment by RobinHerbots** [comment]
@penihel , 

Fixed in version 3.1.3

**Comment by penihel** [comment]
You the man! Thank you

**Comment by penihel** [comment]
I still have a problem.

step by step
1 - Open and run http://jsfiddle.net/8wjsscj0/
2 - Click in "set" button
3 - Focus on "#test3" input, and type 5, the result is ok
4 - now, continuing with the focus on control, type backspace

the result on input is "(12) 12341-234_"
but it was expected just "(12) 1234-1234" again

I clear enough?

**Comment by penihel** [comment]
Seems to be the same problem reported at the end of this issue #604

**Comment by RobinHerbots** [comment]
Yes it is the same as #604
