### ISSUE TITLE
Regex on Android Chrome 37 and 38 - Letters Repeating

### ISSUE THREAD

**Issue by camj256** [RobinHerbots/Inputmask#653]
All input masks except Regex seem to work, and correctly on Chrome 38 beta on Android now, including backspace, so thats good!

I'm not sure if this was mentioned but I believe a lot of previous problems people may have encountered with Chrome on Android were due to this - Just got fixed and released in Chrome Beta 38 on 9/10/14
https://code.google.com/p/chromium/issues/detail?id=118639

However, now on Chrome 37/38 Android whenever I try to enter text on a value with any regex if I enter the letter 'j' for example any other key presses show up as 'j'. So Johnson would be JJJJJJJ.

ex regex for last name (2-15 characters, letters only)
$("#lastName").inputmask('Regex', { regex: "[a-zA-Z]{2,15}"});

Any ideas?

**Comment by RobinHerbots** [comment]
@camj256 , 

When Chrome v38 is out I will verify.

About the regex, this is only occuring on android Chrome?  First guess is a regex malformation (if that is correct english)

**Comment by MaximDubrovin** [comment]
Absolutely the same thing happened for me.

**Comment by camj256** [comment]
Still having the same issue on the newest version, but only with my email regex:

here is my code:
$("#email").inputmask({
        mask: "_{1,20}[._{1,20}][._{1,20}][._{1,20}]@*{1,20}[._{2,6}][._{1,3}]",
        greedy: false,
        regex: "[a-zA-Z0-9._%-]+@[a-zA-Z0-9-]+\.[a-zA-Z]{2,4}",
        isComplete: function(buffer, opts) {return new RegExp(opts.regex).test(buffer.join(''));}
    });

**Comment by camj256** [comment]
This is still a pretty big problem for us. Robin, if you have any insight into why this might be happening I'll look into fixing it myself. I don't have too much time to dedicate to this right now though. Have you been able to reproduce the issue at all? I can give more detail if needed.

**Comment by RobinHerbots** [comment]
@camj256 , 

All input where a compositioin event is fired will not work currently.  

I will try to fix the composition this week.

**Comment by RobinHerbots** [comment]
@camj256 , 

This is fixed in the latest version.  Can you confirm.

**Comment by camj256** [comment]
Its actually a lot worse than 3.1.38.

My original issue is back:
However, now on Chrome 37/38 Android whenever I try to enter text on a value with any regex if I enter the letter 'j' for example any other key presses show up as 'j'. So Johnson would be JJJJJJJ

on 3.1.38 it works sometimes...in some spots, like first and last names, it will show overwrite the first letter with the next letter and so on. Only one letter shows up in firefox android and chrome android. Desktop and apple devices work fine.

Here are the input masks I'm using. Maybe there is a better way to do this:

``` javascript
    $(".first").inputmask('Regex', { regex: "[a-zA-Z]{2,15}", isComplete: function(buffer, opts) {return new RegExp(opts.regex).test(buffer.join(''));} });
    $(".last").inputmask('Regex', { regex: "[a-zA-Z]{2,15}", isComplete: function(buffer, opts) {return new RegExp(opts.regex).test(buffer.join(''));} });
    $(".ageLicensed").inputmask("99",{ "placeholder": "" });
    $(".birthday").inputmask("m/d/y", {"placeholder": "MM/DD/YYYY"});\
    $("#zipFinal").inputmask("99999",{ "placeholder": "" });
    $("#street").inputmask('Regex', { regex: "[0-9].{3,40}", isComplete: function(buffer, opts) {return new RegExp(opts.regex).test(buffer.join(''));} });
    $("#phone").inputmask("mask", {"mask": "(999) 999-9999"});
    $("#email").inputmask({
        mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,3}]",
        greedy: false,
        regex: "[a-zA-Z0-9._%-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,4}",
        isComplete: function(buffer, opts) {return new RegExp(opts.regex).test(buffer.join(''));}
    });
    $("#address").inputmask('Regex', { regex: "[0-9].{3,40}", isComplete: function(buffer, opts) {return new RegExp(opts.regex).test(buffer.join(''));} });
    $('.incidentDate').inputmask("m/y", {"placeholder": "MM/YYYY"});
    $(".accidentDamageTotal").inputmask("integer", { allowMinus: false});
    $(".claimDamageTotal").inputmask("integer", { allowMinus: false});
```

I rely on the isComplete to change the form input to a green border or take away the green border

**Comment by camj256** [comment]
So I re-wrote all the regex ones but its still not working - first, last, email and address are still broken. Either in the way described above, nothing showing up when typing, or scrambled text. 

``` javascript
$(".first").inputmask({mask: "a{2,15}", greedy:false});
    $(".last").inputmask({mask: "a{2,15}", greedy:false});
    $(".ageLicensed").inputmask("99",{ "placeholder": "" });
    $(".birthday").inputmask("m/d/y", {"placeholder": "MM/DD/YYYY"});
    $("#zipFinal").inputmask("99999",{ "placeholder": "" });
    $("#phone").inputmask({"mask": "(999) 999-9999"});
    $("#email").inputmask({
        mask: "*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,3}]",
        greedy: false,
        onBeforePaste: function (pastedValue, opts) {
            pastedValue = pastedValue.toLowerCase();
            return pastedValue.replace("mailto:", "");
        },
        definitions: {
            '*': {
                validator: "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",
                cardinality: 1,
                casing: "lower"
            }
        }
    });
    $("#address").inputmask({mask: "9{1,5} *{1,20}[ *{1,20}][ *{1,20}][ *{1,20}]", greedy: false});
    $('.incidentDate').inputmask("m/y", {"placeholder": "MM/YYYY"});
    $(".accidentDamageTotal").inputmask("integer", { allowMinus: false});
    $(".claimDamageTotal").inputmask("integer", { allowMinus: false});
```

I'm doing some debug work right now, I think the buffer on the regex is not getting the right values. I'm also looking into just writing my own function to do the regex work. If I get it working I'll post it here.

**Comment by camj256** [comment]
Spent some time on this today and wrote my own plugin to do the stuff that doesn't work. Works great across the board so far. Leaves some stuff out as you can see. May make this more in depth later but for now it fills the gap enough for my needs... Re-use whatever you like from it.

``` javascript
(function($){
    var defaults = {
        hasMaskedValue: false,
        isComplete: false
    };
    var settings = {};
    var methods = {
        init: function(args) {
            return this.each(function() {
                var $this = $(this), data = $this.data('clearMask');
                if (!data){
                    $this.on("input", function(){
                        this.value = this.value.replace(args.mask,'');
                        $this.data('clearMask').isComplete = new RegExp(args.regex).test($this.val());
                    });

                    $this.data('clearMask', {
                        hasMaskedValue: true,
                        isComplete: false
                    });
                    data = $this.data('clearMask');
                }
            });
        },
        hasMaskedValue: function() {
            var $this = $(this), data = $this.data('clearMask');

            return data ? data.hasMaskedValue:false;
        },
        isComplete: function() {
            var $this = $(this), data = $this.data('clearMask');

            return data ? data.isComplete:false;
        }
    };

    $.fn.clearMask = function(method, options){
        settings = $.extend({}, defaults, options);
        if (methods[method]) {
            return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
        } else if (typeof method === 'object' || ! method) {
            return methods.init.apply(this, arguments);
        }
    };
})(jQuery);
```

input masks are now:

``` javascript
$(".first").clearMask({mask:/[^a-zA-Z]/g, regex: "[a-zA-Z]{2,15}"});
    $(".last").clearMask({mask:/[^a-zA-Z]/g, regex: "[a-zA-Z]{2,15}"});
    $(".ageLicensed").inputmask("99",{ "placeholder": "" });
    $(".birthday").inputmask("m/d/y", {"placeholder": "MM/DD/YYYY"});
    $("#zipFinal").inputmask("99999",{ "placeholder": "" });
    $("#phone").inputmask({"mask": "(999) 999-9999"});
    $("#email").clearMask({mask:'', regex: "[a-zA-Z0-9._%-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]{2,4}"});
    $("#address").clearMask({mask:'', regex: "[0-9].{3,40}"});
    $('.incidentDate').inputmask("m/y", {"placeholder": "MM/YYYY"});
    $(".accidentDamageTotal").inputmask("integer", { allowMinus: false});
    $(".claimDamageTotal").inputmask("integer", { allowMinus: false});
```

incomplete snippet for how I check for masked values and completness:

``` javascript
$('input').on("keyup", function(){
        if ($(this).inputmask('hasMaskedValue')){
            if ($(this).inputmask("isComplete"))
                $(this).closest('.form-group').removeClass('has-error').addClass('has-success');
            else
                $(this).closest('.form-group').removeClass('has-success');
        }
        else if ($(this).clearMask('hasMaskedValue')){
            if ($(this).clearMask('isComplete')){
                $(this).closest('.form-group').removeClass('has-error').addClass('has-success');
            }
            else
                $(this).closest('.form-group').removeClass('has-success');
        }
```
