### ISSUE TITLE
on pressing the BACKSPACE in integerDigit part, digit part no and integerDigits part no is behaving worngly

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#746]
Step 1: Type the following value  -  123456.078
Step 2: Now keep the cursor in the middle of 5 and 6
Step 3: Now use the BACKSPACE to remove the NO 5
Step 4: Now you can see the NO  5 is converted to 6, it is copying the last integerDigit 6 
Step 5: And also .078 is now .780, this is 78 is also shifted.
Setp 6: Now you can see the the whole nos in the following form  =  123466.780

jsfiddle link
http://jsfiddle.net/BA251281/ug16s3tw/16/

![decimal_mask_issue](https://cloud.githubusercontent.com/assets/2504343/5180717/eb9bea10-74b4-11e4-8d0d-7fb08284784d.png)

**Comment by RobinHerbots** [comment]
Fixed in the current version

**Comment by babupca** [comment]
@RobinHerbots ,

This issue is not fixed. I have tested it just now. Please look into the above jsfiddle link itself. You can reproduce it.

**Comment by RobinHerbots** [comment]
@babupca , 

I followed the exact steps from above and see no problem.   Can you retest or give more details.  Os? Browser? version?   Clear browser cache

**Comment by RobinHerbots** [comment]
@babupca , 

Finally I got to reproduce it  ;-)))   You need to type 123456 then set the caret after the first 0 in the digits and continue 78.  

I will see how I can fix this.

**Comment by RobinHerbots** [comment]
@babupca , 

Can you retry with version 3.1.46

best regards, 
Robin

**Comment by babupca** [comment]
@RobinHerbots ,

It is almost fixed apart from one issue, were the ZERO is not added when all the integerDigits is been deleted.

For Example :

TYPE :  
123456.023 
place the cursor --> 123456(cursor).023 - here delete 123456,
Result now is  .023  
instead of --> 0.023

please check if you have any problems.

**Comment by RobinHerbots** [comment]
@babupca , 

Yes I'm aware of that but that is another issue ;-)
I will fix that soon.

**Comment by babupca** [comment]
@RobinHerbots ,

;-) Yes Robin you are right., it is #722. 

Then this issue is fixed. We can close this defect.

**Comment by babupca** [comment]
@RobinHerbots ,

I think some other problem has surfaced,

Just Type : 
123456.120
Keep the caret before (dot)  123456(here).120 
Now from here press SHIFT+ HOME and select, now 123456 will be selected.
Now press 1
the result is   -- >  112.120 instead of 1.120
I don't know how 12 is getting added to the integerDigit part.

Please let me know, if you require any more info on this.

**Comment by RobinHerbots** [comment]
@babupca , 

Fixed in the latest version

**Comment by babupca** [comment]
Thanks Robin.
